services:
  db:
    image: postgres:15-alpine
    container_name: dauys_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: dauys_db
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dauys_app
    environment:
      - DATABASE_URL=postgresql://admin:adminpassword@db:5432/dauys_db?schema=public
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pgdata:
